name: CMake Clang

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CXX_COMPILER: clang++-17
  C_COMPILER: clang-17

jobs:
  build:
    strategy:
      matrix:
        build_type: [Release, Debug]
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: ${{github.workspace}}/build/${{matrix.build_type}}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Prepare environment
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - && \
        sudo add-apt-repository 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main' && \
        sudo apt update && \
        sudo apt-get install clang-17 lldb-17 lld-17 libc++-17-dev libc++abi-17-dev

    - name: Configure CMake
      run: cmake -B ${{env.BUILD_DIR}} -DCMAKE_CXX_COMPILER=${{env.CXX_COMPILER}} -DCMAKE_C_COMPILER=${{env.C_COMPILER}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      run: cmake --build ${{env.BUILD_DIR}} --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{env.BUILD_DIR}}
      run: ctest -C ${{env.BUILD_TYPE}}
