name: CMake Clang

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CLANG_VERSION: "20"

jobs:
  build:
    strategy:
      matrix:
        build_type: [Release, Debug]
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: ${{github.workspace}}/build/${{matrix.build_type}}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Prepare environment
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-${CLANG_VERSION} lld-${CLANG_VERSION} libc++-${CLANG_VERSION}-dev libc++abi-${CLANG_VERSION}-dev

    - name: Configure CMake
      run: cmake -B ${{env.BUILD_DIR}} -DCMAKE_CXX_COMPILER=clang++-${CLANG_VERSION} -DCMAKE_C_COMPILER=clang-${CLANG_VERSION} -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      run: cmake --build ${{env.BUILD_DIR}}

    - name: Test
      working-directory: ${{env.BUILD_DIR}}
      run: ctest
