name: CMake GCC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GCC_VERSION: "14"

jobs:
  build:
    strategy:
      matrix:
        build_type: [Release, Debug]
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: ${{github.workspace}}/build/${{matrix.build_type}}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Prepare environment
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-${{env.GCC_VERSION}} g++-${{env.GCC_VERSION}}

    - name: Configure CMake
      run: cmake -B ${{env.BUILD_DIR}} -DCMAKE_CXX_COMPILER=g++-${{env.GCC_VERSION}} -DCMAKE_C_COMPILER=gcc-${{env.GCC_VERSION}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      run: cmake --build ${{env.BUILD_DIR}}

    - name: Test
      working-directory: ${{env.BUILD_DIR}}
      run: ctest

    - name: Generate coverage report
      if: ${{matrix.build_type == 'Debug'}}
      working-directory: ${{github.workspace}}
      run: |
        set -eux
        python3 -m pip install --upgrade pip
        python3 -m pip install gcovr
        gcovr --version
        gcovr -r . --gcov-executable gcov-${{env.GCC_VERSION}} --object-directory ${{env.BUILD_DIR}} --exclude 'test/.*' --exclude '3p/.*' --lcov -o coverage.info

    - name: Upload coverage to Codecov
      if: ${{matrix.build_type == 'Debug'}}
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        verbose: true
        files: coverage.info
        token: ${{ secrets.CODECOV_TOKEN }}
