name: Codecov PR upload

on:
  workflow_run:
    workflows: ["CMake GCC"]
    types: [completed]

permissions:
  actions: read
  contents: read

jobs:
  upload:
    if: ${{github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request'}}
    runs-on: ubuntu-latest
    steps:
    - name: Download coverage artifact
      uses: actions/download-artifact@v4
      with:
        name: coverage
        path: coverage
        github-token: ${{secrets.GITHUB_TOKEN}}
        repository: ${{github.repository}}
        run-id: ${{github.event.workflow_run.id}}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        verbose: true
        files: coverage/coverage.info
        token: ${{secrets.CODECOV_TOKEN}}
        override_commit: ${{github.event.workflow_run.head_sha}}
        override_pr: ${{github.event.workflow_run.pull_requests[0].number}}
